ALTER TABLE users ADD COLUMN IF NOT EXISTS cargo text;
ALTER TABLE centros ADD COLUMN IF NOT EXISTS morada text;
ALTER TABLE centros ADD COLUMN IF NOT EXISTS nif text;
ALTER TABLE centros ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE centros ADD COLUMN IF NOT EXISTS telefone text;
